// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const appsyncConfig =  {
  API: {
      GraphQL: {
        endpoint: 'https://dvvkoua5mjdorigkxip66kvqsu.appsync-api.us-east-1.amazonaws.com/graphql',
        region: 'us-east-1',
        defaultAuthMode: 'apiKey',
        apiKey: 'da2-2lwh4tmatrhafpotpudzkbpi4e'
      }
  }
};

export default appsyncConfig;